# Generated by Django 4.2.3 on 2023-08-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_information',
            options={'verbose_name': 'Bilgi', 'verbose_name_plural': 'Bilgiler'},
        ),
        migrations.AlterField(
            model_name='about_information',
            name='informate',
            field=models.CharField(max_length=200, verbose_name='Bilgi'),
        ),
        migrations.AlterField(
            model_name='about_information',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Başlık'),
        ),
    ]
