# Generated by Django 4.2.3 on 2023-08-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_communication_gallery_information_team_members_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Information_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info",
                    models.CharField(max_length=200, null=True, verbose_name="Başlık"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, null=True, verbose_name="Başlık"),
                ),
                (
                    "subtitle",
                    models.CharField(max_length=200, null=True, verbose_name="Başlık"),
                ),
                (
                    "informate",
                    models.CharField(max_length=200, null=True, verbose_name="Bilgi"),
                ),
                (
                    "button",
                    models.CharField(max_length=200, null=True, verbose_name="Bilgi"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, null=True, verbose_name="Başlık"),
                ),
                (
                    "informate",
                    models.CharField(max_length=200, null=True, verbose_name="Bilgi"),
                ),
                (
                    "title_one",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Başlık 1"
                    ),
                ),
                (
                    "informate_one",
                    models.CharField(max_length=200, null=True, verbose_name="Bilgi 1"),
                ),
                (
                    "imageUrl_one",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Resim Url 1"
                    ),
                ),
                (
                    "title_two",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Başlık 2"
                    ),
                ),
                (
                    "informate_two",
                    models.CharField(max_length=200, null=True, verbose_name="Bilgi 2"),
                ),
                (
                    "imageUrl_two",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Resim Url 2"
                    ),
                ),
                (
                    "title_three",
                    models.CharField(
                        max_length=200, null=True, verbose_name="Başlık 3"
                    ),
                ),
                (
                    "informate_three",
                    models.CharField(max_length=200, null=True, verbose_name="Bilgi 3"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="information",
            name="button",
            field=models.CharField(max_length=200, null=True, verbose_name="Bilgi"),
        ),
    ]
