# Generated by Django 4.2.3 on 2023-08-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_information_two_services_information_button"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("surname", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Kişi",
                "verbose_name_plural": "Kişiler",
            },
        ),
        migrations.AlterModelOptions(
            name="communication",
            options={
                "verbose_name": "İletişim",
                "verbose_name_plural": "İletişim Bilgileri",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Galeri", "verbose_name_plural": "Galeri"},
        ),
        migrations.AlterModelOptions(
            name="information",
            options={
                "verbose_name": "Hakkımızda Bilgi",
                "verbose_name_plural": "Hakkımızda Bilgi Sayfası",
            },
        ),
        migrations.AlterModelOptions(
            name="information_two",
            options={
                "verbose_name": "Bilgi 2",
                "verbose_name_plural": "Bilgi Sayfası 2",
            },
        ),
        migrations.AlterModelOptions(
            name="services",
            options={"verbose_name": "Servisler", "verbose_name_plural": "Servisler"},
        ),
        migrations.AlterModelOptions(
            name="team_members",
            options={
                "verbose_name": "Ekip Üyeleri",
                "verbose_name_plural": "Ekip Üyeleri",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonial",
            },
        ),
        migrations.AlterField(
            model_name="information",
            name="button",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Alt Başlık"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="informate",
            field=models.CharField(max_length=20000, null=True, verbose_name="Bilgi"),
        ),
        migrations.AlterField(
            model_name="information_two",
            name="button",
            field=models.CharField(max_length=200, null=True, verbose_name="Buton"),
        ),
        migrations.AlterField(
            model_name="information_two",
            name="info",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Kısa Bilgi"
            ),
        ),
        migrations.AlterField(
            model_name="information_two",
            name="informate",
            field=models.CharField(max_length=20000, null=True, verbose_name="Bilgi"),
        ),
        migrations.AlterField(
            model_name="information_two",
            name="subtitle",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Alt Başlık"
            ),
        ),
        migrations.AlterField(
            model_name="services",
            name="informate_one",
            field=models.CharField(max_length=2000, null=True, verbose_name="Bilgi 1"),
        ),
        migrations.AlterField(
            model_name="services",
            name="informate_three",
            field=models.CharField(max_length=2000, null=True, verbose_name="Bilgi 3"),
        ),
        migrations.AlterField(
            model_name="services",
            name="informate_two",
            field=models.CharField(max_length=2000, null=True, verbose_name="Bilgi 2"),
        ),
    ]
