# Generated by Django 4.2.3 on 2023-08-15 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_user_alter_communication_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="surname",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Konu")),
                ("text", models.CharField(max_length=2500, verbose_name="İçerik")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Tarih"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mesaj",
                "verbose_name_plural": "Mesajlar",
            },
        ),
    ]
