# Generated by Django 4.2.3 on 2023-10-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_ip_alter_user_name_alter_user_surname_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plaka",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaka_karakter", models.CharField(max_length=10)),
                ("tespit_zamani", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
