# Generated by Django 4.2.3 on 2023-11-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0008_plaka"),
    ]

    operations = [
        migrations.CreateModel(
            name="plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaka_numarasi", models.CharField(max_length=10)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("saat", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
