# Generated by Django 4.2.3 on 2023-11-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0010_plate_plaka_gorseli"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Plaka",
        ),
    ]
