# Generated by Django 4.2.3 on 2023-11-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0011_delete_plaka"),
    ]

    operations = [
        migrations.DeleteModel(
            name="plate",
        ),
    ]
