# Generated by Django 4.2.3 on 2023-11-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0012_delete_plate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plaka_numarasi", models.CharField(max_length=10)),
                ("tarih", models.DateTimeField(auto_now_add=True)),
                ("saat", models.DateTimeField(auto_now_add=True)),
                (
                    "plaka_gorseli",
                    models.ImageField(null=True, upload_to="plaka_gorselleri/"),
                ),
            ],
        ),
    ]
