# Generated by Django 4.2.3 on 2023-11-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0013_plate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plate",
            name="saat",
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="plate",
            name="tarih",
            field=models.DateField(auto_now_add=True),
        ),
    ]
