# Generated by Django 4.2.3 on 2023-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0015_alter_plate_plaka_gorseli"),
    ]

    operations = [
        migrations.CreateModel(
            name="detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benzerlik_orani", models.CharField(max_length=30)),
                ("tarih", models.DateField(auto_now_add=True)),
                ("saat", models.TimeField(auto_now_add=True)),
                ("gorsel", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "At Tespiti",
                "verbose_name_plural": "At Tespiti",
            },
        ),
        migrations.CreateModel(
            name="plate_detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("benzerlik_orani", models.CharField(max_length=30)),
                ("isim", models.CharField(max_length=15)),
                ("tarih", models.DateField(auto_now_add=True)),
                ("saat", models.TimeField(auto_now_add=True)),
                ("gorsel", models.ImageField(blank=True, null=True, upload_to="")),
            ],
            options={
                "verbose_name": "Plaka Tespiti",
                "verbose_name_plural": "Plaka Tespiti",
            },
        ),
        migrations.AlterModelOptions(
            name="plate",
            options={"verbose_name": "Plaka", "verbose_name_plural": "Plakalar"},
        ),
    ]
